### ISSUE TITLE
there are no textures

### ISSUE THREAD

**Issue by AcornGR** [Garten/sourcecraft#7]
there are the minecraft textures in the hammer editor but not on the blocks. is there a way so that they are applied to the blocks automatically?

**Comment by Garten** [comment]
Hi, they should be the right textures (having the correct name) for example these: https://gamebanana.com/textures/5830

Then they have to be in the right folder:
"If you put them into the "texture/" folder, sourcecraft makes sure that a copy is at the correct directory needed for the Hammer Editor (unlesss you wish otherwise)."
If so it should work. You can check that went wrong: In hammer editor with the map loaded: press Shift+A and the left click on a surface: It should tell you "minecraft_original/stonebrick" or similar. You may also use the buttons (of the opened dialog) "Browse" and "Replace" to manually change the textures to the minecraft textures you already have.

**Comment by krysaleksiejuk** [comment]
I am having an issue where the minecraft texture are not an option in the details tab of soursecraft. The map transfers and if i select an object it has the right name, but it just does not have a texture.
